#!/bin/bash
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt01 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt02 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt03 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt04 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt05 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt06 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt07 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt08 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt09 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt10 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt11 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt12 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt13 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt14 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt15 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt16 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt17 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt18 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt19 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt20 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt21 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt22 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt23 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt24 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt25 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt26 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt27 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt28 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt29 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt30 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt31 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt32 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt33 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt34 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt35 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt36 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt37 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt38 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt39 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  AWT awt40 lqpht &
