#!/bin/bash
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw01 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw02 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw03 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw04 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw05 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw06 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw07 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw08 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw09 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw10 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw11 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw12 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw13 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw14 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw15 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw16 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw17 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw18 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw19 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw20 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw21 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw22 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw23 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw24 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw25 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw26 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw27 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw28 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw29 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw30 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw31 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw32 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw33 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw34 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw35 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw36 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw37 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw38 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw39 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw40 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw41 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw42 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw43 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw44 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw45 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw46 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw47 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw48 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw49 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw50 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw51 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw52 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw53 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NSW nsw54 lqpht &
