#!/bin/bash
# Already started 1-4
#Rscript MaxEntBayesScriptSpecies.R --args  NZ nz01 lqpht &
#Rscript MaxEntBayesScriptSpecies.R --args  NZ nz02 lqpht &
#Rscript MaxEntBayesScriptSpecies.R --args  NZ nz03 lqpht &
#Rscript MaxEntBayesScriptSpecies.R --args  NZ nz04 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz05 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz06 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz07 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz08 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz09 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz10 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz11 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz12 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz13 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz14 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz15 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz16 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz17 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz18 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz19 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz20 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz21 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz22 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz23 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz24 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz25 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz26 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz27 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz28 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz29 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz30 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz31 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz32 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz33 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz34 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz35 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz36 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz37 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz38 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz39 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz40 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz41 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz42 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz43 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz44 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz45 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz46 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz47 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz48 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz49 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz50 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz51 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  NZ nz52 lqpht &
