#!/bin/bash
Rscript MaxEntBayesScriptSpecies.R --args  SA sa01 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa02 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa03 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa04 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa05 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa06 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa07 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa08 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa09 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa10 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa11 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa12 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa13 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa14 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa15 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa16 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa17 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa18 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa19 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa20 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa21 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa22 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa23 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa24 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa25 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa26 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa27 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa28 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa29 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SA sa30 lqpht &
