#!/bin/bash
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi01 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi02 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi03 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi04 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi05 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi06 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi07 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi08 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi09 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi10 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi11 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi12 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi13 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi14 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi15 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi16 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi17 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi18 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi19 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi20 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi21 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi22 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi23 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi24 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi25 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi26 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi27 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi28 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi29 lqpht &
Rscript MaxEntBayesScriptSpecies.R --args  SWI swi30 lqpht &
